136 edit platform modal pending
openlibraryenvironment/gokb-ui pull request #70
Opened 2022-03-16 16:02 UTC by philboeselager

2022-03-21 15:35 UTC, philboeselager commented
depends on https://github.com/openlibraryenvironment/gokb/pull/496

2022-03-23 12:37 UTC, hornmo requested changes
There seems to be an issue with the displaying of the error messages:

`<v-col v-if="c.id">
 {{ $t('component.platform.conflict.noProvider', [c.id]) }}` (line 48/49)

Should be for `!c.id` (no provider id) and the parameter should be `c.platformId` instead of `c.id`.

2022-03-23 12:37 UTC, hornmo commented on src/shared/services/platform-services/platform-services.js
> +    }, {});
I don't think we need this filtering via fieldList here. Just put only name & primaryUrl into `data` and create the params from that.

2022-03-24 08:36 UTC, philboeselager commented on src/shared/services/platform-services/platform-services.js
> +    }, {});
True. Came out of the idea if we'd need a such functionality in other methods, but it's pure overload. Has been simplified now.

2022-03-24 08:37 UTC, philboeselager commented
> There seems to be an issue with the displaying of the error messages:
> 
> `<v-col v-if="c.id"> {{ $t('component.platform.conflict.noProvider', [c.id]) }}` (line 48/49)
> 
> Should be for `!c.id` (no provider id) and the parameter should be `c.platformId` instead of `c.id`.

Changed.

2022-03-24 11:51 UTC, hornmo approved these changes

2022-03-24 11:51 UTC, merged